import {json2satrec,propagate,gstime,eciToGeodetic,degreesLat,degreesLong} from 'satellite.js';
export const RADIUS=45;
export function groundDistance(a,b){const r=Math.PI/180,p=a.lat*r,q=b.lat*r,d=(b.lon-a.lon)*r;const h=Math.sin((q-p)/2)**2+Math.cos(p)*Math.cos(q)*Math.sin(d/2)**2;return 6371.0088*2*Math.atan2(Math.sqrt(Math.min(1,h)),Math.sqrt(Math.max(0,1-h)));}
export function bearing(a,b){const r=Math.PI/180,p=a.lat*r,q=b.lat*r,d=(b.lon-a.lon)*r;return Math.atan2(Math.sin(d)*Math.cos(q),Math.cos(p)*Math.sin(q)-Math.sin(p)*Math.cos(q)*Math.cos(d));}
export function records(data,now=Date.now()){let skipped=0;const sats=[];for(const o of data){try{const epoch=Date.parse(o.EPOCH+'Z');if(!Number.isFinite(epoch)||Math.abs(now-epoch)>7*86400000){skipped++;continue;}const rec=json2satrec(o);if(rec.error){skipped++;continue;}sats.push({id:String(o.NORAD_CAT_ID),name:String(o.OBJECT_NAME||o.NORAD_CAT_ID),epoch,rec});}catch{skipped++;}}return {sats,skipped};}
export function position(s,t){try{const date=new Date(t),p=propagate(s.rec,date);if(!p?.position||s.rec.error)return null;const g=eciToGeodetic(p.position,gstime(date));const v={lat:degreesLat(g.latitude),lon:degreesLong(g.longitude),alt:g.height};return Object.values(v).every(Number.isFinite)&&v.alt>0?v:null;}catch{return null;}}
// Refine each local minimum between coarse samples; near-tangent passes can be shorter than a sample interval.
export function crossing(s,loc,start,end){let best={distance:Infinity,time:start};const d=t=>{const p=position(s,t);return p?groundDistance(loc,p):Infinity;};const times=[];for(let t=start;t<=end;t+=5000)times.push(t);if(times.at(-1)!==end)times.push(end);const ds=times.map(d);for(let i=0;i<times.length;i++){if(ds[i]<best.distance)best={distance:ds[i],time:times[i]};if(i>0&&i<times.length-1&&ds[i]<=ds[i-1]&&ds[i]<=ds[i+1]){let l=times[i-1],r=times[i+1];for(let j=0;j<18;j++){const a=l+(r-l)/3,b=r-(r-l)/3;if(d(a)<d(b))r=b;else l=a;}const t=(l+r)/2,v=d(t);if(v<best.distance)best={distance:v,time:t};}}
return best.distance<=RADIUS?best:null;}
