CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),lat REAL,lon REAL,radius_km INTEGER NOT NULL DEFAULT 45 CHECK(radius_km BETWEEN 10 AND 1000 AND radius_km%5=0),alert_mode TEXT NOT NULL DEFAULT 'all',satellite_ids TEXT NOT NULL DEFAULT '[]',enabled INTEGER NOT NULL DEFAULT 0,verified INTEGER NOT NULL DEFAULT 0,revision INTEGER NOT NULL DEFAULT 0,last_check INTEGER,last_sent INTEGER,last_error TEXT,lease_until INTEGER NOT NULL DEFAULT 0);
INSERT OR IGNORE INTO settings(id) VALUES(1);
CREATE TABLE IF NOT EXISTS events(satellite_id TEXT PRIMARY KEY,sent_at INTEGER NOT NULL);
