'use client';
import {useEffect,useRef,useState} from 'react';
import {Satellite,LocateFixed,Radio,Send,ArrowUpRight,RefreshCw,ShieldCheck,ChevronDown,Check,LoaderCircle} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
type Loc={lat:number;lon:number};type Sat={id:string;name:string;lat:number;lon:number;alt:number;distance:number;bearing:number};
type Frame={now:number;valid:number;inside:number;skipped:number;near:Sat[]};
type Service={locationSet:boolean;enabled:boolean;lat:number;lon:number;lastCheck:number|null;lastError:string|null;lastSent:number|null;configured:boolean};
export default function Home(){
const [loc,setLoc]=useState<Loc|null>(null),[lat,setLat]=useState(''),[lon,setLon]=useState(''),[frame,setFrame]=useState<Frame|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[fetched,setFetched]=useState<number|null>(null),[clock,setClock]=useState(0),[selected,setSelected]=useState(''),[range,setRange]=useState(450);
const [serviceUrl,setServiceUrl]=useState(''),[key,setKey]=useState(''),[service,setService]=useState<Service|null>(null),[busy,setBusy]=useState(false),[serviceError,setServiceError]=useState(''),[serviceNotice,setServiceNotice]=useState('');
const worker=useRef<Worker|null>(null),locationRef=useRef<Loc|null>(null);
useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('orbit-location')||'null');if(v&&Number.isFinite(v.lat)&&Math.abs(v.lat)<=90&&Number.isFinite(v.lon)&&Math.abs(v.lon)<=180){setLoc(v);locationRef.current=v;setLat(String(v.lat));setLon(String(v.lon));}setServiceUrl(localStorage.getItem('orbit-service')||'');}catch{};const w=new Worker('/tracker-worker.js');worker.current=w;w.onmessage=e=>setFrame(e.data);w.onerror=()=>setError('Tracking could not start. Reload the page to retry.');const id=setInterval(()=>setClock(Date.now()),1000);setClock(Date.now());return()=>{w.terminate();clearInterval(id);};},[]);
async function load(){setLoading(true);setError('');try{const r=await fetch('/api/catalog');const j=await r.json();if(!r.ok)throw Error(j.error||'Catalog unavailable');setFetched(j.fetchedAt);worker.current?.postMessage({data:j.data,loc:locationRef.current});}catch(e){setError(e instanceof Error?e.message:'Could not load satellites.');}finally{setLoading(false);}}
useEffect(()=>{load();const id=setInterval(load,7200000);return()=>clearInterval(id);},[]);
function apply(v:Loc){setLoc(v);locationRef.current=v;setLat(v.lat.toFixed(5));setLon(v.lon.toFixed(5));setFrame(null);worker.current?.postMessage({loc:v});try{localStorage.setItem('orbit-location',JSON.stringify(v));}catch{}setNotice('Location set. To move Telegram alerts here, use “Save alert location” below.');}
function manual(e:React.FormEvent){e.preventDefault();const a=Number(lat),b=Number(lon);if(!lat.trim()||!lon.trim()||!Number.isFinite(a)||!Number.isFinite(b)||Math.abs(a)>90||Math.abs(b)>180){setNotice('Enter latitude from −90 to 90 and longitude from −180 to 180.');return;}apply({lat:a,lon:b});}
function locate(){setNotice('Finding your location…');if(!navigator.geolocation){setNotice('Location is unavailable. Enter coordinates instead.');return;}navigator.geolocation.getCurrentPosition(p=>{apply({lat:p.coords.latitude,lon:p.coords.longitude});setNotice(`Location set (accuracy about ${Math.round(p.coords.accuracy)} m). This center stays fixed until you update it.`);},()=>setNotice('Location access was unavailable. Allow location in your browser or enter coordinates.'),{enableHighAccuracy:true,timeout:15000,maximumAge:60000});}
async function call(path:string,body?:unknown){const u=new URL(serviceUrl);if(u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error('Enter the HTTPS address of your alert service, without a path.');if(!key.trim())throw Error('Enter your alert service access key.');const r=await fetch(u.origin+path,{method:body===undefined?'GET':'POST',headers:{Authorization:`Bearer ${key.trim()}`,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)});const j=await r.json();if(!r.ok)throw Error(j.error||'Alert service could not complete this request.');return j;}
async function action(kind:string,value?:boolean){setBusy(true);setServiceError('');setServiceNotice('');try{if(kind==='connect'){const s=await call('/status');setService(s);localStorage.setItem('orbit-service',serviceUrl);setServiceNotice('Connected. Verify the alert location, then send yourself a test.');}else if(kind==='test'){await call('/test',{});setServiceNotice('Test message sent. Check your Telegram chat.');}else if(kind==='save'&&loc){setService(await call('/settings',{...loc,enabled:service?.enabled??false}));setServiceNotice('Telegram alert location updated.');}else if(kind==='toggle'&&service){setService(await call('/settings',{lat:service.lat,lon:service.lon,enabled:value}));setServiceNotice(value?'Alerts enabled. The background checker will report its next check shortly.':'Telegram alerts paused.');}}catch(e){setServiceError(e instanceof Error?e.message:'Could not connect.');if(kind==='connect')setService(null);}finally{setBusy(false);}}
useEffect(()=>{if(!service)return;const id=setInterval(()=>call('/status').then(setService).catch(()=>setServiceError('Connection lost. Alert status could not be refreshed.')),30000);return()=>clearInterval(id);},[serviceUrl,key,!!service]);
const fresh=!!frame&&clock-frame.now<15000&&!error;const points=frame?.near.filter(s=>s.distance<=range)||[];const picked=frame?.near.find(s=>s.id===selected)||frame?.near[0];const healthy=!!service?.enabled&&!!service.lastCheck&&clock-service.lastCheck<180000&&!service.lastError&&!serviceError;
return <main><header className="top"><a className="brand" href="/"><span className="brand-icon"><Satellite size={23}/></span>ORBIT<span>WATCH</span></a><div className="top-right"><span className="private"><ShieldCheck size={15}/> Personal observatory</span><span className="utc">{clock?new Date(clock).toISOString().slice(11,19):'--:--:--'} UTC</span></div></header>
<div className="page-heading"><div><p className="eyebrow">YOUR PATCH OF SKY</p><h1>Catch what passes overhead.</h1><p className="intro">Live orbital positions. A 45 km boundary. Telegram alerts.</p></div><div className="radius-tag"><span>MONITORING RADIUS</span><strong>45 <small>km</small></strong><span>Ground distance from your location</span></div></div>
<div className="workspace"><section className="tracking"><div className="section-head"><h2><Radio size={18}/> Local satellite radar</h2><span className={`badge ${fresh?'green':''}`}>{fresh?'Tracking live':loading?'Loading catalog':!loc?'Location needed':'Waiting for data'}</span></div>
<div className="radar"><div className="radar-meta"><span>{loc?`${loc.lat.toFixed(3)}°, ${loc.lon.toFixed(3)}°`:'LOCATION NOT SET'}</span><span>GROUND TRACK · NORTH UP</span></div><svg viewBox="0 0 640 520" role="img" aria-label={`Satellite ground positions within ${range} kilometers, north at top. The green circle marks your 45 kilometer alert boundary.`}><defs><radialGradient id="radar-bg"><stop stopColor="#12352f"/><stop offset="1" stopColor="#0b171e"/></radialGradient></defs><circle cx="320" cy="260" r="210" fill="url(#radar-bg)"/>{[.25,.5,.75,1].map(v=><circle key={v} cx="320" cy="260" r={210*v} fill="none" stroke="#264047" strokeDasharray={v===1?'0':'3 6'}/>)}<path d="M110 260H530M320 50V470M171.5 111.5L468.5 408.5M171.5 408.5L468.5 111.5" stroke="#22373e"/><circle cx="320" cy="260" r={210*45/range} fill="#84f0b318" stroke="#a5f4b6" strokeWidth="1.5"/><text x="320" y="32" textAnchor="middle">N</text><text x="556" y="265">E</text><text x="320" y="501" textAnchor="middle">S</text><text x="78" y="265">W</text><circle cx="320" cy="260" r="5" fill="#b4ffce"/><text x="331" y="278" className="you">YOU</text><text x="327" y={253-210*45/range} className="boundary-label">45 km boundary</text>{loc&&points.map(s=>{const x=320+Math.sin(s.bearing)*s.distance/range*210,y=260-Math.cos(s.bearing)*s.distance/range*210;return <g key={s.id} onClick={()=>setSelected(s.id)} className="sat-point"><title>{s.name}: {s.distance.toFixed(1)} km ground distance</title><circle cx={x} cy={y} r={s.id===picked?.id?8:4} fill={s.distance<=45?'#b4ffce':'#69b8ec'} stroke={s.id===picked?.id?'#c4eaff':'none'} strokeWidth="2"/></g>;})}</svg>
{!loc&&<div className="radar-empty"><LocateFixed size={30}/><strong>Your sky starts here</strong><p>Set your location to see nearby satellites.</p><button className="primary" onClick={locate}><LocateFixed size={17}/> Use my location</button></div>}
<div className="radar-bottom"><span><i/> 45 km alert zone <b/> Satellite</span><div className="zoom"><button aria-label="Zoom in" disabled={range<=90} onClick={()=>setRange(range/5)}>+</button><span>{range} km view</span><button aria-label="Zoom out" disabled={range>=2250} onClick={()=>setRange(range*5)}>−</button></div></div></div>
<div className="metrics"><div><span>Inside your boundary</span><strong>{fresh?frame?.inside:'—'} <small>satellites</small></strong></div><div><span>Propagated successfully</span><strong>{fresh?frame?.valid.toLocaleString():'—'} <small>tracked</small></strong></div><div><span>Nearest ground track</span><strong>{fresh&&picked?picked.distance.toFixed(0):'—'} <small>km</small></strong></div></div>
{error&&<div className="error" role="alert">{error}<button onClick={load} disabled={loading}>Retry catalog</button></div>}
<div className="nearby"><div className="section-head"><h2>Nearest satellites</h2><span className="muted">Within 2,500 km · {fresh?'updated every 2s':'waiting'}</span></div><Table><TableHeader><TableRow><TableHead>Satellite</TableHead><TableHead>Ground distance</TableHead><TableHead>Altitude</TableHead><TableHead>Boundary</TableHead></TableRow></TableHeader><TableBody>{fresh&&frame?.near.slice(0,8).map(s=><TableRow key={s.id} className={s.id===picked?.id?'selected-row':''} onClick={()=>setSelected(s.id)}><TableCell><strong>{s.name}</strong><span className="catalog-id">NORAD {s.id}</span></TableCell><TableCell>{s.distance.toFixed(1)} km</TableCell><TableCell>{s.alt.toFixed(0)} km</TableCell><TableCell><span className={s.distance<=45?'in-zone':'muted'}>{s.distance<=45?'Inside zone':'Outside'}</span></TableCell></TableRow>)}</TableBody></Table>{(!fresh||!frame?.near.length)&&<p className="empty-text">{!loc?'Choose your location to begin tracking.':loading?'Retrieving the active satellite catalog…':error?'Tracking is unavailable until the catalog loads.':!frame?'Calculating current satellite positions…':'No tracked satellites within 2,500 km right now.'}</p>}</div></section>
<aside><section className="panel"><div className="panel-title"><span className="step">01</span><h2>Your location</h2></div><p>Center your fixed 45 km circle.</p><button className="location-button" onClick={locate}><LocateFixed size={18}/> Use my current location</button><form onSubmit={manual}><div className="coordinate-inputs"><label>Latitude<input type="number" step="any" min="-90" max="90" placeholder="e.g. 28.6139" value={lat} onChange={e=>setLat(e.target.value)} required/></label><label>Longitude<input type="number" step="any" min="-180" max="180" placeholder="e.g. 77.2090" value={lon} onChange={e=>setLon(e.target.value)} required/></label></div><button className="secondary full" type="submit">Set coordinates</button></form>{notice&&<p className="feedback" role="status">{notice}</p>}<p className="small-note">Coordinates stay on this device until you save them to your alert service. Location does not follow you automatically.</p></section>
<section className="panel telegram"><div className="panel-title"><span className="step">02</span><h2>Telegram alerts</h2><Send size={19}/></div><div className={`connection-status ${healthy?'connected':''}`}>{healthy?<Check size={16}/>:<span className="status-dot"/>}{healthy?'Background monitoring active':service?.enabled?'Enabled · awaiting healthy check':service?'Connected · alerts paused':'Not connected'}</div><p>Get a message when a ground track crosses your circle—even with this website closed.</p><details open={!service}><summary>Connect your alert service <ChevronDown size={15}/></summary><label>Alert service URL<input type="url" placeholder="https://your-alerts.workers.dev" value={serviceUrl} onChange={e=>{setServiceUrl(e.target.value);setService(null);}}/></label><label>Access key<input autoComplete="off" type="password" placeholder="Your private service key" value={key} onChange={e=>{setKey(e.target.value);setService(null);}}/></label><button className="primary full" disabled={busy} onClick={()=>action('connect')}>{busy?<LoaderCircle size={16} className="spin"/>:<Send size={16}/>} Connect Telegram service</button><p className="small-note">The key is kept in this tab only. Your Telegram bot token stays on the alert server.</p></details>
{service&&<div className="service-controls"><div className="toggle-row"><label htmlFor="alerts">Send pass notifications</label><Switch id="alerts" checked={service.enabled} disabled={busy||!service.configured||!service.locationSet} onCheckedChange={v=>action('toggle',v)}/></div><p className="small-note">Alert center: {service.lat.toFixed(4)}°, {service.lon.toFixed(4)}° · 45 km</p><button className="secondary full" disabled={!loc||busy} onClick={()=>action('save')}>Save alert location</button><button className="secondary full" disabled={busy} onClick={()=>action('test')}>Send me a Telegram test</button><p className="small-note">Last background check: {service.lastCheck?new Date(service.lastCheck).toLocaleTimeString():'Not received yet'}</p>{service.lastError&&<p className="error">{service.lastError}</p>}</div>}
{serviceError&&<p className="error" role="alert">{serviceError}</p>}{serviceNotice&&<p className="feedback" role="status">{serviceNotice}</p>}
<details className="setup"><summary>First-time Telegram setup <ArrowUpRight size={15}/></summary><ol><li>Open <a href="https://t.me/BotFather" target="_blank" rel="noreferrer">@BotFather</a> in Telegram and create a bot with <code>/newbot</code>.</li><li>Start a private chat with your new bot and send <code>/start</code>.</li><li>Deploy the background checker in your Cloudflare account. Its setup guide explains how to store your bot token, verify your private chat ID, and set the schedule.</li><li>Connect its URL and access key above, save your location, send a test, then turn on alerts.</li></ol><a className="download" href="/orbit-alert-service.zip" download>Download background checker & guide <ArrowUpRight size={15}/></a><p className="small-note">Background service hosting is separate and may incur charges. No Telegram alerts are active until setup is complete.</p></details></section>
<section className="explain"><h3>What counts as “overhead”?</h3><p>The point directly below a satellite must fall inside your 45 km circle. A satellite can be hundreds of kilometers above you and still qualify.</p><p>This is an orbital prediction, not a promise of visibility. Clouds, daylight and satellite brightness affect what you can see.</p></section></aside></div>
<footer><span>ORBIT WATCH <span className="footer-sep">/</span> Personal satellite monitor</span><span>Orbital data: <a href="https://celestrak.org/NORAD/elements/" target="_blank" rel="noreferrer">CelesTrak</a> · SGP4</span><span>{fetched?`Catalog retrieved ${new Date(fetched).toLocaleTimeString()}`:'Catalog not loaded'}{frame?.skipped?` · ${frame.skipped} stale/invalid records excluded`:''}</span></footer><p className="footnote">Coverage is CelesTrak’s public active-satellite catalog, not every object in orbit. Positions are estimates; records over 7 days old are excluded. Telegram checks run each minute and report predicted close passes up to a minute early or shortly afterward; delivery is not exact to the second.</p></main>;
}
