'use client';
import {useEffect,useRef,useState} from 'react';
type Point={id?:string;lat:number;lon:number};
export function WorldMap({points,track,loc,radius,selected,favorites,onSelect}:{points:Point[];track:Point[];loc:Point|null;radius:number;selected:string;favorites:string[];onSelect:(id:string)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),[land,setLand]=useState<any>(null),[mapError,setMapError]=useState(false),[zoom,setZoom]=useState(1),[center,setCenter]=useState({lon:0,lat:0});
 const drag=useRef<{x:number;y:number;lon:number;lat:number;moved:boolean}|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/world-land.geojson',{signal:controller.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setLand).catch(()=>{if(!controller.signal.aborted)setMapError(true);});return()=>controller.abort();},[]);
 const xy=(p:Point)=>({x:480+(((p.lon-center.lon+540)%360)-180)*960/360*zoom,y:240-(p.lat-center.lat)*480/180*zoom});
 useEffect(()=>{const c=canvas.current;if(!c)return;const g=c.getContext('2d');if(!g)return;
 g.clearRect(0,0,960,480);g.fillStyle='#081522';g.fillRect(0,0,960,480);
 const project=(p:number[],offset=0)=>[480+(p[0]-center.lon+offset)*960/360*zoom,240-(p[1]-center.lat)*480/180*zoom];
 g.strokeStyle='#173340';g.lineWidth=1;for(let lon=-180;lon<=180;lon+=30){for(const offset of [-360,0,360]){const [x]=project([lon,0],offset);g.beginPath();g.moveTo(x,0);g.lineTo(x,480);g.stroke();}}for(let lat=-90;lat<=90;lat+=30){const [,y]=project([0,lat]);g.beginPath();g.moveTo(0,y);g.lineTo(960,y);g.stroke();}
 g.fillStyle='#173544';g.strokeStyle='#39606a';
 for(const f of land?.features||[]){const polygons=f.geometry.type==='Polygon'?[f.geometry.coordinates]:f.geometry.coordinates;for(const poly of polygons){for(const offset of [-360,0,360]){g.beginPath();for(const ring of poly){ring.forEach((p:number[],i:number)=>{const [x,y]=project(p,offset);if(i===0)g.moveTo(x,y);else g.lineTo(x,y);});g.closePath();}g.fill('evenodd');g.stroke();}}}
 function line(ps:Point[],color:string,width=2){g!.strokeStyle=color;g!.lineWidth=width;g!.beginPath();let last:ReturnType<typeof xy>|null=null;for(const p of ps){const a=xy(p);if(!last||Math.abs(a.x-last.x)>480*zoom)g!.moveTo(a.x,a.y);else g!.lineTo(a.x,a.y);last=a;}g!.stroke();}
 if(loc){const circle:Point[]=[],d=radius/6371.0088,p=loc.lat*Math.PI/180,l=loc.lon*Math.PI/180;for(let i=0;i<=180;i++){const b=i*2*Math.PI/180,q=Math.asin(Math.sin(p)*Math.cos(d)+Math.cos(p)*Math.sin(d)*Math.cos(b)),lon=l+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(p),Math.cos(d)-Math.sin(p)*Math.sin(q));circle.push({lat:q*180/Math.PI,lon:lon*180/Math.PI});}line(circle,'#ffc36b');const a=xy(loc);g.fillStyle='#ffc36b';g.beginPath();g.arc(a.x,a.y,4,0,Math.PI*2);g.fill();}
 line(track,'#ecf6ff');for(const p of points){const a=xy(p),picked=p.id===selected,fav=favorites.includes(p.id||'');g.fillStyle=picked?'#fff':fav?'#ffc36b':'#67dded';g.globalAlpha=picked||fav?1:.55;g.beginPath();g.arc(a.x,a.y,picked?6:fav?3.5:1.5,0,Math.PI*2);g.fill();}g.globalAlpha=1;
 },[points,track,loc,radius,selected,favorites,land,center,zoom]);
 return <section id="world-map" className="orbit-section"><div className="section-head"><h2>World map</h2><span className="muted">{points.length.toLocaleString()} satellite positions</span></div><p>Click a satellite to inspect it. Drag to pan; zoom in to separate nearby tracks.</p><div className="world-canvas"><canvas ref={canvas} width={960} height={480} aria-label="World satellite map. Use the searchable satellite directory below for keyboard selection." onPointerDown={e=>{drag.current={x:e.clientX,y:e.clientY,...center,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{const d=drag.current;if(!d)return;const w=e.currentTarget.getBoundingClientRect().width,dx=e.clientX-d.x,dy=e.clientY-d.y;if(Math.hypot(dx,dy)>4)d.moved=true;if(d.moved)setCenter({lon:((d.lon-dx/w*360/zoom+540)%360)-180,lat:Math.max(-90,Math.min(90,d.lat+dy/w*360/zoom))});}} onPointerUp={e=>{const d=drag.current;drag.current=null;if(!d||d.moved)return;const b=e.currentTarget.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*960,y=(e.clientY-b.top)/b.height*480;let best:Point|null=null,dist=14*960/b.width;for(const p of points){const a=xy(p),n=Math.hypot(a.x-x,a.y-y);if(n<dist){best=p;dist=n;}}if(best?.id)onSelect(best.id);}} onPointerCancel={()=>drag.current=null}/></div><div className="map-controls"><button className="secondary" aria-label="Zoom out world map" disabled={zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z/2))}>−</button><span>{zoom}×</span><button className="secondary" aria-label="Zoom in world map" disabled={zoom>=16} onClick={()=>setZoom(z=>Math.min(16,z*2))}>+</button><button className="secondary" onClick={()=>{setCenter({lon:0,lat:0});setZoom(1);}}>Whole Earth</button><button className="secondary" disabled={!loc} onClick={()=>{if(loc){setCenter(loc);setZoom(8);}}}>My area</button></div><p className="small-note">Amber: favorites and your {radius} km boundary · White: selected satellite and its next 90 minutes of ground track. Map positions require fresh orbital records. <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth public-domain coastlines</a>.</p>{mapError&&<p role="alert" className="error">Coastlines could not load. Satellite positions and the observation boundary remain available. Reload to retry.</p>}</section>;
}
